### PR TITLE
Fix:  Notes aren't Persistent #7

### LINKED ISSUE #7: Notes aren't Persistent
right now the notes don't persist. If i close the extension popup they are gone and must be scraped again. Update the extension so that the notes will stick around. The scrape button will need to remain available so that I can scrape and overwrite the current notes.

### PR DESCRIPTION
**Pull request by R055A**
Fixes #7 

All the manual testing I did for this PR is passing.

### CODE REVIEW

**Comment by Beasta** [comment]
i've got two accounts for testing. After scraping one account it worked great. Scraped the other etherscan account  and it worked fine until I closed the popup. When I reopened the popup it was showing the notes from the first account.

**Comment by R055A** [comment]
> i've got two accounts for testing. After scraping one account it worked great. Scraped the other etherscan account and it worked fine until I closed the popup. When I reopened the popup it was showing the notes from the first account.

Thank you for letting me know this. I was unaware that this was a requirement, and I have only tested with one account.

* Did the data initially display in the table for both the first and second account before closing the pop-up when using the second account after using the first account?
* Can you give a detailed explanation of the behaviour that you want between accounts, please

UPDATE: I have tested what I think you are describing, and I did not experience any noticeable bug.

**Comment by Beasta** [comment]
i removed the extension and then reinstalled instead of just refreshing and it seems to have solved my problem.  Looks good @R055A

**Comment by Beasta** [comment]
oops i guess i need to merge rather than close

**Pull request merged**
